/**
 * CI/CD Pipeline Generator
 * Generates complete GitLab CI/CD and GitHub Actions pipelines
 */

export type CICDProvider = 'gitlab' | 'github' | 'jenkins';

export interface CICDConfig {
  provider: CICDProvider;
  includeLint?: boolean;
  includeTest?: boolean;
  includeSecurity?: boolean;
  includeDeploy?: boolean;
  environments?: ('dev' | 'staging' | 'production')[];
  ansibleVersion?: string;
}

/**
 * Generate GitLab CI/CD pipeline
 */
export function generateGitLabCI(config: CICDConfig): string {
  const {
    includeLint = true,
    includeTest = true,
    includeSecurity = true,
    includeDeploy = true,
    environments = ['staging', 'production'],
    ansibleVersion = '2.14'
  } = config;

  let pipeline = `# GitLab CI/CD Pipeline for Ansible
# Generated by CortexOps

stages:`;

  const stages: string[] = [];
  if (includeLint) stages.push('  - lint');
  if (includeTest) stages.push('  - test');
  if (includeSecurity) stages.push('  - security');
  if (includeDeploy) stages.push('  - deploy');

  pipeline += '\n' + stages.join('\n') + '\n\n';

  pipeline += `variables:
  ANSIBLE_VERSION: "${ansibleVersion}"
  ANSIBLE_FORCE_COLOR: "true"
  ANSIBLE_HOST_KEY_CHECKING: "false"

`;

  pipeline += `.ansible_base:
  image: cytopia/ansible:${ansibleVersion}
  before_script:
    - pip install ansible-lint yamllint
    - ansible --version
  cache:
    paths:
      - .ansible/

`;

  if (includeLint) {
    pipeline += `# ==========================================
# LINT STAGE
# ==========================================

ansible-lint:
  extends: .ansible_base
  stage: lint
  script:
    - echo "🔍 Running Ansible Lint..."
    - ansible-lint playbooks/*.yml || true
  allow_failure: false
  tags:
    - ansible

yaml-lint:
  extends: .ansible_base
  stage: lint
  script:
    - echo "🔍 Running YAML Lint..."
    - yamllint -c .yamllint playbooks/ roles/
  allow_failure: true
  tags:
    - ansible

syntax-check:
  extends: .ansible_base
  stage: lint
  script:
    - echo "🔍 Running Syntax Check..."
    - |
      for playbook in playbooks/*.yml; do
        echo "Checking $playbook..."
        ansible-playbook "$playbook" --syntax-check
      done
  tags:
    - ansible

`;
  }

  if (includeTest) {
    pipeline += `# ==========================================
# TEST STAGE
# ==========================================

dry-run:
  extends: .ansible_base
  stage: test
  script:
    - echo "🧪 Running Dry-Run (Check Mode)..."
    - |
      for playbook in playbooks/*.yml; do
        echo "Testing $playbook..."
        ansible-playbook "$playbook" --check -i inventories/staging/hosts.yml || true
      done
  allow_failure: true
  tags:
    - ansible

molecule-test:
  extends: .ansible_base
  stage: test
  script:
    - echo "🧪 Running Molecule Tests..."
    - pip install molecule molecule-docker
    - cd roles/ && molecule test
  allow_failure: true
  only:
    - merge_requests
    - main
  tags:
    - ansible
    - molecule

`;
  }

  if (includeSecurity) {
    pipeline += `# ==========================================
# SECURITY STAGE
# ==========================================

security-scan:
  extends: .ansible_base
  stage: security
  script:
    - echo "🔒 Running Security Scan..."
    - pip install ansible-security-scanner
    - |
      echo "Scanning for hardcoded secrets..."
      grep -r "password\\|secret\\|token" playbooks/ roles/ --color=always || true
  allow_failure: true
  tags:
    - ansible
    - security

vault-check:
  extends: .ansible_base
  stage: security
  script:
    - echo "🔐 Checking for unencrypted sensitive data..."
    - |
      if grep -r "vault_password" playbooks/ roles/; then
        echo "⚠️  Warning: Found unencrypted vault passwords!"
      fi
  allow_failure: true
  tags:
    - ansible
    - security

`;
  }

  if (includeDeploy) {
    environments.forEach(env => {
      const isProduction = env === 'production';

      pipeline += `# Deploy to ${env}
deploy-${env}:
  extends: .ansible_base
  stage: deploy
  script:
    - echo "🚀 Deploying to ${env.toUpperCase()}..."
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - |
      ansible-playbook playbooks/site.yml \\
        -i inventories/${env}/hosts.yml \\
        --extra-vars "environment=${env}" \\
        ${isProduction ? '--limit production' : ''}
  environment:
    name: ${env}
    ${isProduction ? 'url: https://example.com' : ''}
  ${isProduction ? `when: manual
  only:
    - main
    - tags` : `only:
    - main
    - develop`}
  tags:
    - ansible
    - deploy

`;
    });
  }

  pipeline += `# ==========================================
# ROLLBACK (Manual)
# ==========================================

rollback:
  extends: .ansible_base
  stage: deploy
  script:
    - echo "⏮️  Rolling back deployment..."
    - ansible-playbook playbooks/rollback.yml -i inventories/production/hosts.yml
  when: manual
  only:
    - main
  tags:
    - ansible
    - rollback
`;

  return pipeline;
}

/**
 * Generate GitHub Actions workflow
 */
export function generateGitHubActions(config: CICDConfig): string {
  const {
    includeLint = true,
    includeTest = true,
    includeSecurity = true,
    includeDeploy = true,
    environments = ['staging', 'production'],
    ansibleVersion = '2.14'
  } = config;

  let workflow = `name: Ansible CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  ANSIBLE_VERSION: ${ansibleVersion}
  ANSIBLE_FORCE_COLOR: true
  ANSIBLE_HOST_KEY_CHECKING: false

jobs:
`;

  if (includeLint) {
    workflow += `  lint:
    name: Lint Ansible Playbooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install ansible==${{ env.ANSIBLE_VERSION }} ansible-lint yamllint

      - name: Run ansible-lint
        run: |
          ansible-lint playbooks/*.yml

      - name: Run yamllint
        run: |
          yamllint -c .yamllint playbooks/ roles/

      - name: Syntax check
        run: |
          for playbook in playbooks/*.yml; do
            echo "Checking $playbook..."
            ansible-playbook "$playbook" --syntax-check
          done

`;
  }

  if (includeTest) {
    workflow += `  test:
    name: Test Ansible Playbooks
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: |
          pip install ansible==${{ env.ANSIBLE_VERSION }}

      - name: Run dry-run (check mode)
        run: |
          for playbook in playbooks/*.yml; do
            echo "Testing $playbook..."
            ansible-playbook "$playbook" --check -i inventories/staging/hosts.yml || true
          done

`;
  }

  if (includeSecurity) {
    workflow += `  security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Scan for secrets
        run: |
          echo "🔒 Scanning for hardcoded secrets..."
          grep -r "password\\|secret\\|token" playbooks/ roles/ --color=always || true

      - name: Check for unencrypted sensitive data
        run: |
          if grep -r "vault_password" playbooks/ roles/; then
            echo "⚠️  Warning: Found unencrypted vault passwords!"
          fi

`;
  }

  if (includeDeploy) {
    environments.forEach(env => {
      const isProduction = env === 'production';

      workflow += `  deploy-${env}:
    name: Deploy to ${env}
    runs-on: ubuntu-latest
    needs: [lint, test, security]
    ${isProduction ? `if: github.ref == 'refs/heads/main' && github.event_name == 'push'` : `if: github.event_name == 'push'`}
    environment:
      name: ${env}
      ${isProduction ? `url: https://example.com` : ''}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: |
          pip install ansible==${{ env.ANSIBLE_VERSION }}

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "\${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to ${env}
        run: |
          ansible-playbook playbooks/site.yml \\
            -i inventories/${env}/hosts.yml \\
            --extra-vars "environment=${env}" \\
            ${isProduction ? '--limit production' : ''}

`;
    });
  }

  return workflow;
}

/**
 * Generate Jenkins Pipeline
 */
export function generateJenkinsPipeline(config: CICDConfig): string {
  const {
    includeLint = true,
    includeTest = true,
    includeSecurity = true,
    includeDeploy = true,
    environments = ['staging', 'production'],
    ansibleVersion = '2.14'
  } = config;

  let pipeline = `pipeline {
    agent any

    environment {
        ANSIBLE_VERSION = '${ansibleVersion}'
        ANSIBLE_FORCE_COLOR = 'true'
        ANSIBLE_HOST_KEY_CHECKING = 'false'
    }

    stages {
`;

  if (includeLint) {
    pipeline += `        stage('Lint') {
            steps {
                echo '🔍 Running Ansible Lint...'
                sh '''
                    pip install ansible==\${ANSIBLE_VERSION} ansible-lint yamllint
                    ansible-lint playbooks/*.yml
                    yamllint -c .yamllint playbooks/ roles/
                '''
            }
        }

`;
  }

  if (includeTest) {
    pipeline += `        stage('Test') {
            steps {
                echo '🧪 Running Tests...'
                sh '''
                    for playbook in playbooks/*.yml; do
                        echo "Testing \$playbook..."
                        ansible-playbook "\$playbook" --check -i inventories/staging/hosts.yml || true
                    done
                '''
            }
        }

`;
  }

  if (includeSecurity) {
    pipeline += `        stage('Security') {
            steps {
                echo '🔒 Running Security Scan...'
                sh '''
                    grep -r "password\\|secret\\|token" playbooks/ roles/ --color=always || true
                '''
            }
        }

`;
  }

  if (includeDeploy) {
    environments.forEach(env => {
      const isProduction = env === 'production';

      pipeline += `        stage('Deploy to ${env}') {
            ${isProduction ? `when {
                branch 'main'
            }` : ''}
            steps {
                echo '🚀 Deploying to ${env.toUpperCase()}...'
                sh '''
                    ansible-playbook playbooks/site.yml \\
                        -i inventories/${env}/hosts.yml \\
                        --extra-vars "environment=${env}" \\
                        ${isProduction ? '--limit production' : ''}
                '''
            }
        }

`;
    });
  }

  pipeline += `    }

    post {
        success {
            echo '✅ Pipeline completed successfully!'
        }
        failure {
            echo '❌ Pipeline failed!'
        }
    }
}`;

  return pipeline;
}

/**
 * Generate CI/CD configuration files
 */
export function generateCICDFiles(config: CICDConfig): Record<string, string> {
  const files: Record<string, string> = {};

  switch (config.provider) {
    case 'gitlab':
      files['.gitlab-ci.yml'] = generateGitLabCI(config);
      break;
    case 'github':
      files['.github/workflows/ansible.yml'] = generateGitHubActions(config);
      break;
    case 'jenkins':
      files['Jenkinsfile'] = generateJenkinsPipeline(config);
      break;
  }

  // Add common configuration files
  files['.yamllint'] = `---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  indentation:
    spaces: 2
    indent-sequences: yes
  comments:
    min-spaces-from-content: 1
`;

  files['.ansible-lint'] = `---
skip_list:
  - role-name
  - yaml[line-length]
  - name[casing]

warn_list:
  - experimental
  - ignore-errors

exclude_paths:
  - .github/
  - .gitlab/
  - venv/
`;

  return files;
}

/**
 * Generate complete CI/CD setup with multi-environment support
 */
export function generateCompleteCICDSetup(config: CICDConfig): string {
  const files = generateCICDFiles(config);

  let output = `# CI/CD Pipeline Configuration\n\n`;
  output += `## Provider: ${config.provider.toUpperCase()}\n\n`;
  output += `## Files Generated:\n\n`;

  Object.keys(files).forEach(filename => {
    output += `### ${filename}\n\`\`\`yaml\n${files[filename]}\`\`\`\n\n`;
  });

  return output;
}
