/**
 * Multi-Environment Support Generator
 * Generates inventory files and configurations for dev/staging/production environments
 */

export type Environment = 'dev' | 'staging' | 'production';

export interface EnvironmentConfig {
  name: Environment;
  domain: string;
  sslEnabled: boolean;
  backupRetention: number;
  logLevel: 'debug' | 'info' | 'warning' | 'error';
  hosts: EnvironmentHost[];
}

export interface EnvironmentHost {
  name: string;
  ip: string;
  role: 'webserver' | 'database' | 'loadbalancer' | 'monitoring' | 'cache';
  user?: string;
}

/**
 * Generate inventory file for specific environment
 */
export function generateEnvironmentInventory(config: EnvironmentConfig): string {
  const { name, domain, sslEnabled, backupRetention, hosts } = config;

  // Group hosts by role
  const hostsByRole: Record<string, EnvironmentHost[]> = {};
  hosts.forEach(host => {
    if (!hostsByRole[host.role]) {
      hostsByRole[host.role] = [];
    }
    hostsByRole[host.role].push(host);
  });

  let inventory = `# ${name.toUpperCase()} Environment Inventory
# Domain: ${domain}
# Generated by CortexOps

all:
  children:
`;

  // Generate groups
  Object.entries(hostsByRole).forEach(([role, roleHosts]) => {
    const groupName = role === 'webserver' ? 'webservers' :
                      role === 'database' ? 'databases' :
                      role === 'loadbalancer' ? 'loadbalancers' :
                      role === 'monitoring' ? 'monitoring' :
                      role === 'cache' ? 'cache' : role;

    inventory += `    ${groupName}:
      hosts:
`;

    roleHosts.forEach(host => {
      inventory += `        ${host.name}:
          ansible_host: ${host.ip}
          ansible_user: ${host.user || 'ubuntu'}
`;
    });

    inventory += '\n';
  });

  inventory += `  vars:
    environment: ${name}
    domain_name: ${domain}
    ssl_enabled: ${sslEnabled}
    backup_retention_days: ${backupRetention}
    ansible_python_interpreter: /usr/bin/python3
`;

  return inventory;
}

/**
 * Generate group_vars/all.yml for environment
 */
export function generateAllVars(config: EnvironmentConfig): string {
  const { name, domain, logLevel } = config;

  return `---
# Global variables for ${name.toUpperCase()} environment

environment: ${name}
domain_name: ${domain}
log_level: ${logLevel}

# Ansible Configuration
ansible_python_interpreter: /usr/bin/python3
ansible_user: ubuntu
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

# Vault Configuration
vault_addr: ${name === 'production' ? 'https' : 'http'}://vault${name === 'production' ? '' : `-${name}`}.${domain}:8200
use_vault: ${name === 'production' ? 'true' : 'false'}

# Monitoring
monitoring_enabled: true
prometheus_url: http://prometheus${name === 'production' ? '' : `-${name}`}.${domain}:9090
grafana_url: http://grafana${name === 'production' ? '' : `-${name}`}.${domain}:3000

# Logging
loki_url: http://loki${name === 'production' ? '' : `-${name}`}.${domain}:3100
log_retention_days: ${name === 'production' ? '30' : name === 'staging' ? '14' : '7'}

# Backup Configuration
backup_enabled: ${name === 'production' ? 'true' : name === 'staging' ? 'true' : 'false'}
backup_retention_days: ${config.backupRetention}
backup_schedule: "${name === 'production' ? '0 2 * * *' : '0 3 * * *'}"

# Performance Tuning
max_connections: ${name === 'production' ? '1000' : name === 'staging' ? '500' : '100'}
worker_processes: ${name === 'production' ? '8' : name === 'staging' ? '4' : '2'}

# Security
security_hardening: ${name === 'production' ? 'strict' : name === 'staging' ? 'moderate' : 'basic'}
fail2ban_enabled: ${name === 'production' || name === 'staging' ? 'true' : 'false'}
firewall_enabled: ${name === 'production' || name === 'staging' ? 'true' : 'false'}
`;
}

/**
 * Generate group_vars for specific role
 */
export function generateRoleVars(environment: Environment, role: string): string {
  const envConfig = {
    production: { replicas: 3, cache: '1GB', timeout: 300 },
    staging: { replicas: 2, cache: '512MB', timeout: 180 },
    dev: { replicas: 1, cache: '256MB', timeout: 60 }
  };

  const config = envConfig[environment];

  if (role === 'webservers') {
    return `---
# Webserver configuration for ${environment.toUpperCase()}

nginx_worker_processes: ${config.replicas * 2}
nginx_worker_connections: ${environment === 'production' ? '1024' : '512'}
nginx_keepalive_timeout: ${config.timeout}

# SSL/TLS
ssl_enabled: ${environment === 'production' || environment === 'staging' ? 'true' : 'false'}
ssl_certificate: /etc/ssl/certs/${environment}-cert.pem
ssl_certificate_key: /etc/ssl/private/${environment}-key.pem
ssl_protocols: "TLSv1.2 TLSv1.3"

# Caching
enable_cache: ${environment === 'production' ? 'true' : 'false'}
cache_size: ${config.cache}

# Logging
access_log_enabled: true
error_log_level: ${environment === 'production' ? 'error' : 'info'}
`;
  } else if (role === 'databases') {
    return `---
# Database configuration for ${environment.toUpperCase()}

db_name: mydb_${environment}
db_user: dbuser_${environment}
db_max_connections: ${environment === 'production' ? '200' : environment === 'staging' ? '100' : '50'}
db_shared_buffers: ${environment === 'production' ? '2GB' : environment === 'staging' ? '1GB' : '256MB'}

# Replication
db_replication_enabled: ${environment === 'production' ? 'true' : 'false'}
db_replication_slots: ${config.replicas - 1}

# Backup
db_backup_enabled: ${environment === 'production' || environment === 'staging' ? 'true' : 'false'}
db_backup_schedule: "${environment === 'production' ? '0 1 * * *' : '0 2 * * *'}"
db_backup_retention_days: ${environment === 'production' ? '30' : environment === 'staging' ? '14' : '7'}

# Performance
db_work_mem: ${environment === 'production' ? '16MB' : '4MB'}
db_maintenance_work_mem: ${environment === 'production' ? '256MB' : '64MB'}
`;
  } else if (role === 'monitoring') {
    return `---
# Monitoring configuration for ${environment.toUpperCase()}

prometheus_retention_time: ${environment === 'production' ? '30d' : environment === 'staging' ? '15d' : '7d'}
prometheus_scrape_interval: ${environment === 'production' ? '15s' : '30s'}

grafana_admin_password: "{{ lookup('hashi_vault', 'secret=secret/${environment}/grafana:admin_password') }}"

# Alerting
alertmanager_enabled: ${environment === 'production' ? 'true' : 'false'}
alert_email: ops-${environment}@example.com
`;
  }

  return `---
# ${role} configuration for ${environment.toUpperCase()}
`;
}

/**
 * Generate complete multi-environment structure
 */
export function generateMultiEnvironmentStructure(environments: EnvironmentConfig[]): Record<string, string> {
  const files: Record<string, string> = {};

  environments.forEach(env => {
    // Generate inventory
    files[`inventories/${env.name}/hosts.yml`] = generateEnvironmentInventory(env);

    // Generate group_vars
    files[`inventories/${env.name}/group_vars/all.yml`] = generateAllVars(env);
    files[`inventories/${env.name}/group_vars/webservers.yml`] = generateRoleVars(env.name, 'webservers');
    files[`inventories/${env.name}/group_vars/databases.yml`] = generateRoleVars(env.name, 'databases');
    files[`inventories/${env.name}/group_vars/monitoring.yml`] = generateRoleVars(env.name, 'monitoring');
  });

  // Generate ansible.cfg
  files['ansible.cfg'] = `[defaults]
inventory = ./inventories/production/hosts.yml
roles_path = ./roles
host_key_checking = False
retry_files_enabled = False
gathering = smart
fact_caching = jsonfile
fact_caching_connection = /tmp/ansible_facts
fact_caching_timeout = 3600

[privilege_escalation]
become = True
become_method = sudo
become_user = root
become_ask_pass = False

[ssh_connection]
pipelining = True
control_path = /tmp/ansible-%%r@%%h:%%p
`;

  // Generate environment switcher script
  files['switch-env.sh'] = `#!/bin/bash
# Environment Switcher for Ansible
# Usage: ./switch-env.sh <dev|staging|production>

set -e

ENV=$1

if [ -z "$ENV" ]; then
    echo "Usage: $0 <dev|staging|production>"
    exit 1
fi

if [ ! -d "inventories/$ENV" ]; then
    echo "Error: Environment '$ENV' does not exist"
    exit 1
fi

echo "Switching to $ENV environment..."

# Update ansible.cfg
sed -i "s|inventory = ./inventories/.*/hosts.yml|inventory = ./inventories/$ENV/hosts.yml|" ansible.cfg

echo "✅ Successfully switched to $ENV environment"
echo "Current inventory: inventories/$ENV/hosts.yml"
`;

  // Generate deployment script
  files['deploy.sh'] = `#!/bin/bash
# Deployment Script with Multi-Environment Support
# Usage: ./deploy.sh <env> <playbook>

set -e

ENV=\${1:-staging}
PLAYBOOK=\${2:-site.yml}

echo "🚀 Deploying to $ENV environment..."
echo "📋 Playbook: $PLAYBOOK"

# Switch environment
./switch-env.sh $ENV

# Run playbook
ansible-playbook playbooks/$PLAYBOOK \\
  -i inventories/$ENV/hosts.yml \\
  --extra-vars "environment=$ENV" \\
  --diff

echo "✅ Deployment to $ENV completed successfully!"
`;

  return files;
}

/**
 * Generate default environment configurations
 */
export function generateDefaultEnvironments(): EnvironmentConfig[] {
  return [
    {
      name: 'dev',
      domain: 'dev.example.com',
      sslEnabled: false,
      backupRetention: 3,
      logLevel: 'debug',
      hosts: [
        { name: 'web01-dev', ip: '10.0.1.10', role: 'webserver' },
        { name: 'db01-dev', ip: '10.0.2.10', role: 'database' }
      ]
    },
    {
      name: 'staging',
      domain: 'staging.example.com',
      sslEnabled: true,
      backupRetention: 7,
      logLevel: 'info',
      hosts: [
        { name: 'web01-staging', ip: '10.0.1.20', role: 'webserver' },
        { name: 'web02-staging', ip: '10.0.1.21', role: 'webserver' },
        { name: 'db01-staging', ip: '10.0.2.20', role: 'database' },
        { name: 'monitor-staging', ip: '10.0.3.20', role: 'monitoring' }
      ]
    },
    {
      name: 'production',
      domain: 'example.com',
      sslEnabled: true,
      backupRetention: 30,
      logLevel: 'warning',
      hosts: [
        { name: 'web01-prod', ip: '172.16.1.10', role: 'webserver' },
        { name: 'web02-prod', ip: '172.16.1.11', role: 'webserver' },
        { name: 'web03-prod', ip: '172.16.1.12', role: 'webserver' },
        { name: 'db01-prod', ip: '172.16.2.10', role: 'database' },
        { name: 'db02-prod', ip: '172.16.2.11', role: 'database' },
        { name: 'lb01-prod', ip: '172.16.4.10', role: 'loadbalancer' },
        { name: 'monitor-prod', ip: '172.16.3.10', role: 'monitoring' }
      ]
    }
  ];
}

/**
 * Generate playbook with environment-specific logic
 */
export function generateEnvironmentAwarePlaybook(environments: Environment[]): string {
  return `---
# Environment-Aware Playbook
# Automatically adapts to dev/staging/production environments

- name: Pre-deployment checks
  hosts: all
  become: yes
  gather_facts: yes

  pre_tasks:
    - name: Verify environment variable is set
      assert:
        that:
          - environment is defined
          - environment in ['dev', 'staging', 'production']
        fail_msg: "Environment must be set to dev, staging, or production"

    - name: Display deployment information
      debug:
        msg: |
          ========================================
          Deploying to: {{ environment | upper }}
          Domain: {{ domain_name }}
          SSL Enabled: {{ ssl_enabled }}
          ========================================

    - name: Check disk space
      shell: df -h / | tail -1 | awk '{print $5}' | sed 's/%//'
      register: disk_usage
      changed_when: false

    - name: Fail if disk space is low
      fail:
        msg: "Disk space critical: {{ disk_usage.stdout }}% used"
      when: disk_usage.stdout | int > 90

- name: Deploy application
  hosts: webservers
  become: yes
  tasks:
    - name: Deploy to {{ environment }}
      debug:
        msg: "Deploying application to {{ environment }} environment"

    - name: Include environment-specific variables
      include_vars: "{{ playbook_dir }}/../inventories/{{ environment }}/group_vars/webservers.yml"

    - name: Configure application
      template:
        src: app-config.j2
        dest: /etc/app/config.yml
        mode: '0644'

- name: Configure database
  hosts: databases
  become: yes
  tasks:
    - name: Configure database for {{ environment }}
      debug:
        msg: "Configuring database for {{ environment }}"

    - name: Include environment-specific database variables
      include_vars: "{{ playbook_dir }}/../inventories/{{ environment }}/group_vars/databases.yml"

- name: Post-deployment tasks
  hosts: all
  become: yes
  tasks:
    - name: Generate deployment report
      copy:
        content: |
          Deployment Report
          ================
          Environment: {{ environment }}
          Date: {{ ansible_date_time.iso8601 }}
          Hosts: {{ ansible_play_hosts | join(', ') }}
          User: {{ ansible_user_id }}
        dest: /var/log/deployment-{{ ansible_date_time.date }}.log
        mode: '0644'

    - name: Send notification (production only)
      debug:
        msg: "Sending deployment notification..."
      when: environment == 'production'
`;
}
