/**
 * Professional HTML Report Generator
 * Generates comprehensive reports for playbooks, deployments, and analytics
 */

import { PlaybookMetrics, PredictiveInsight } from './predictiveAnalytics';

export interface ReportData {
  title: string;
  subtitle?: string;
  generated_at: string;
  organization?: string;
  project?: string;
  sections: ReportSection[];
}

export interface ReportSection {
  title: string;
  type: 'metrics' | 'insights' | 'table' | 'chart' | 'text' | 'code';
  content: any;
}

/**
 * HTML Report Generator
 */
export class HTMLReportGenerator {
  /**
   * Generate playbook analysis report
   */
  static generatePlaybookReport(
    playbookName: string,
    playbookContent: string,
    metrics: PlaybookMetrics,
    insights: PredictiveInsight[]
  ): string {
    const report: ReportData = {
      title: `Playbook Analysis Report: ${playbookName}`,
      subtitle: 'Generated by CortexOps Predictive Analytics',
      generated_at: new Date().toISOString(),
      sections: [
        {
          title: 'Executive Summary',
          type: 'metrics',
          content: {
            'Complexity Score': `${metrics.complexity_score}/100`,
            'Security Score': `${metrics.security_score}/100`,
            'Maintainability': `${metrics.maintainability_score}/100`,
            'Risk Level': metrics.risk_level.toUpperCase(),
            'Estimated Runtime': `${metrics.estimated_runtime_minutes} minutes`
          }
        },
        {
          title: 'Predictive Insights',
          type: 'insights',
          content: insights
        },
        {
          title: 'Playbook Content',
          type: 'code',
          content: playbookContent
        }
      ]
    };

    return this.generateHTML(report);
  }

  /**
   * Generate deployment report
   */
  static generateDeploymentReport(
    deploymentData: {
      environment: string;
      version: string;
      status: string;
      hosts_total: number;
      hosts_success: number;
      hosts_failed: number;
      duration_seconds: number;
      deployed_by: string;
      deployed_at: string;
    }
  ): string {
    const successRate = (deploymentData.hosts_success / deploymentData.hosts_total * 100).toFixed(1);

    const report: ReportData = {
      title: `Deployment Report: ${deploymentData.environment}`,
      subtitle: `Version ${deploymentData.version}`,
      generated_at: new Date().toISOString(),
      sections: [
        {
          title: 'Deployment Summary',
          type: 'metrics',
          content: {
            'Environment': deploymentData.environment.toUpperCase(),
            'Version': deploymentData.version,
            'Status': deploymentData.status,
            'Success Rate': `${successRate}%`,
            'Duration': `${Math.floor(deploymentData.duration_seconds / 60)} minutes`,
            'Deployed By': deploymentData.deployed_by,
            'Deployed At': new Date(deploymentData.deployed_at).toLocaleString()
          }
        },
        {
          title: 'Host Status',
          type: 'table',
          content: {
            headers: ['Metric', 'Count', 'Percentage'],
            rows: [
              ['Total Hosts', deploymentData.hosts_total, '100%'],
              ['Success', deploymentData.hosts_success, `${successRate}%`],
              ['Failed', deploymentData.hosts_failed, `${(100 - parseFloat(successRate)).toFixed(1)}%`]
            ]
          }
        }
      ]
    };

    return this.generateHTML(report);
  }

  /**
   * Generate usage analytics report
   */
  static generateAnalyticsReport(
    organization: string,
    period: string,
    data: {
      total_playbooks: number;
      total_deployments: number;
      success_rate: number;
      avg_complexity: number;
      top_users: Array<{ name: string; count: number }>;
      deployment_timeline: Array<{ date: string; count: number }>;
    }
  ): string {
    const report: ReportData = {
      title: 'Usage Analytics Report',
      subtitle: `${organization} - ${period}`,
      generated_at: new Date().toISOString(),
      organization,
      sections: [
        {
          title: 'Key Metrics',
          type: 'metrics',
          content: {
            'Total Playbooks Generated': data.total_playbooks,
            'Total Deployments': data.total_deployments,
            'Deployment Success Rate': `${data.success_rate}%`,
            'Average Complexity Score': `${data.avg_complexity}/100`
          }
        },
        {
          title: 'Top Contributors',
          type: 'table',
          content: {
            headers: ['User', 'Playbooks Generated'],
            rows: data.top_users.map(u => [u.name, u.count])
          }
        },
        {
          title: 'Deployment Timeline',
          type: 'chart',
          content: {
            type: 'line',
            data: data.deployment_timeline
          }
        }
      ]
    };

    return this.generateHTML(report);
  }

  /**
   * Core HTML generation
   */
  private static generateHTML(report: ReportData): string {
    const styles = this.getStyles();
    const header = this.generateHeader(report);
    const sections = report.sections.map(s => this.generateSection(s)).join('\n');

    return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${report.title}</title>
  <style>${styles}</style>
</head>
<body>
  <div class="container">
    ${header}
    ${sections}
    ${this.generateFooter()}
  </div>
  <script>${this.getScripts()}</script>
</body>
</html>`;
  }

  private static generateHeader(report: ReportData): string {
    return `
<header class="report-header">
  <div class="logo">
    <div class="logo-icon">⚡</div>
    <span class="logo-text">CortexOps</span>
  </div>
  <h1>${report.title}</h1>
  ${report.subtitle ? `<p class="subtitle">${report.subtitle}</p>` : ''}
  <div class="metadata">
    <span class="meta-item">🕐 Generated: ${new Date(report.generated_at).toLocaleString()}</span>
    ${report.organization ? `<span class="meta-item">🏢 ${report.organization}</span>` : ''}
    ${report.project ? `<span class="meta-item">📁 ${report.project}</span>` : ''}
  </div>
</header>`;
  }

  private static generateSection(section: ReportSection): string {
    return `
<section class="report-section">
  <h2 class="section-title">${section.title}</h2>
  <div class="section-content">
    ${this.generateSectionContent(section)}
  </div>
</section>`;
  }

  private static generateSectionContent(section: ReportSection): string {
    switch (section.type) {
      case 'metrics':
        return this.generateMetrics(section.content);
      case 'insights':
        return this.generateInsights(section.content);
      case 'table':
        return this.generateTable(section.content);
      case 'chart':
        return this.generateChart(section.content);
      case 'text':
        return `<div class="text-content">${section.content}</div>`;
      case 'code':
        return this.generateCode(section.content);
      default:
        return '<p>Unknown section type</p>';
    }
  }

  private static generateMetrics(metrics: Record<string, any>): string {
    const items = Object.entries(metrics).map(([key, value]) => `
      <div class="metric-card">
        <div class="metric-label">${key}</div>
        <div class="metric-value">${value}</div>
      </div>
    `).join('');

    return `<div class="metrics-grid">${items}</div>`;
  }

  private static generateInsights(insights: PredictiveInsight[]): string {
    if (!insights || insights.length === 0) {
      return '<p class="no-data">No insights available</p>';
    }

    const items = insights.map(insight => {
      const severityClass = `insight-${insight.severity}`;
      const typeIcon = this.getInsightIcon(insight.type);

      return `
      <div class="insight-card ${severityClass}">
        <div class="insight-header">
          <span class="insight-icon">${typeIcon}</span>
          <span class="insight-title">${insight.title}</span>
          <span class="insight-badge ${severityClass}">${insight.severity}</span>
        </div>
        <p class="insight-description">${insight.description}</p>
        <div class="insight-recommendation">
          <strong>💡 Recommendation:</strong> ${insight.recommendation}
        </div>
        <div class="insight-meta">
          <span>Confidence: ${insight.confidence}%</span>
          <span>Impact: ${insight.impact}</span>
        </div>
      </div>`;
    }).join('');

    return `<div class="insights-list">${items}</div>`;
  }

  private static generateTable(data: { headers: string[]; rows: any[][] }): string {
    const headers = data.headers.map(h => `<th>${h}</th>`).join('');
    const rows = data.rows.map(row =>
      `<tr>${row.map(cell => `<td>${cell}</td>`).join('')}</tr>`
    ).join('');

    return `
<table class="data-table">
  <thead><tr>${headers}</tr></thead>
  <tbody>${rows}</tbody>
</table>`;
  }

  private static generateChart(data: { type: string; data: any }): string {
    const chartId = `chart-${Math.random().toString(36).substr(2, 9)}`;
    return `
<div class="chart-container">
  <canvas id="${chartId}" data-chart='${JSON.stringify(data)}'></canvas>
  <p class="chart-note">Chart visualization placeholder - Implement with Chart.js or similar library</p>
</div>`;
  }

  private static generateCode(code: string): string {
    const escaped = code
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;');

    return `<pre class="code-block"><code>${escaped}</code></pre>`;
  }

  private static generateFooter(): string {
    return `
<footer class="report-footer">
  <p>Generated by <strong>CortexOps</strong> - Enterprise Ansible Automation Platform</p>
  <p class="footer-links">
    <a href="https://cortexops.dev">Website</a> •
    <a href="https://docs.cortexops.dev">Documentation</a> •
    <a href="https://cortexops.dev/support">Support</a>
  </p>
</footer>`;
  }

  private static getInsightIcon(type: string): string {
    const icons: Record<string, string> = {
      optimization: '⚡',
      risk: '⚠️',
      best_practice: '✅',
      performance: '🚀',
      security: '🔒'
    };
    return icons[type] || '📊';
  }

  private static getStyles(): string {
    return `
* { margin: 0; padding: 0; box-sizing: border-box; }
body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
  background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%);
  color: #cbd5e1;
  line-height: 1.6;
  padding: 2rem;
}
.container { max-width: 1200px; margin: 0 auto; background: #1e293b; border-radius: 12px; box-shadow: 0 20px 60px rgba(0,0,0,0.5); }
.report-header {
  background: linear-gradient(135deg, #06b6d4 0%, #0284c7 100%);
  color: white;
  padding: 3rem 2rem;
  border-radius: 12px 12px 0 0;
}
.logo { display: flex; align-items: center; gap: 0.5rem; margin-bottom: 1rem; }
.logo-icon { font-size: 2rem; }
.logo-text { font-size: 1.5rem; font-weight: bold; }
.report-header h1 { font-size: 2.5rem; margin-bottom: 0.5rem; }
.subtitle { font-size: 1.2rem; opacity: 0.9; margin-bottom: 1rem; }
.metadata { display: flex; gap: 2rem; flex-wrap: wrap; font-size: 0.9rem; }
.meta-item { opacity: 0.95; }
.report-section { padding: 2rem; border-bottom: 1px solid #334155; }
.report-section:last-of-type { border-bottom: none; }
.section-title { font-size: 1.8rem; color: #06b6d4; margin-bottom: 1.5rem; }
.metrics-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 1.5rem;
}
.metric-card {
  background: #0f172a;
  padding: 1.5rem;
  border-radius: 8px;
  border-left: 4px solid #06b6d4;
}
.metric-label { color: #94a3b8; font-size: 0.9rem; margin-bottom: 0.5rem; }
.metric-value { color: white; font-size: 2rem; font-weight: bold; }
.insights-list { display: flex; flex-direction: column; gap: 1rem; }
.insight-card {
  background: #0f172a;
  padding: 1.5rem;
  border-radius: 8px;
  border-left: 4px solid #06b6d4;
}
.insight-card.insight-warning { border-left-color: #f59e0b; }
.insight-card.insight-critical { border-left-color: #ef4444; }
.insight-header {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  margin-bottom: 1rem;
}
.insight-icon { font-size: 1.5rem; }
.insight-title { flex: 1; font-size: 1.1rem; font-weight: 600; color: white; }
.insight-badge {
  padding: 0.25rem 0.75rem;
  border-radius: 12px;
  font-size: 0.75rem;
  font-weight: 600;
  text-transform: uppercase;
}
.insight-badge.insight-info { background: #0ea5e9; color: white; }
.insight-badge.insight-warning { background: #f59e0b; color: white; }
.insight-badge.insight-critical { background: #ef4444; color: white; }
.insight-description { margin-bottom: 1rem; color: #cbd5e1; }
.insight-recommendation {
  background: #334155;
  padding: 1rem;
  border-radius: 6px;
  margin-bottom: 1rem;
}
.insight-meta {
  display: flex;
  gap: 1.5rem;
  font-size: 0.85rem;
  color: #94a3b8;
}
.data-table {
  width: 100%;
  border-collapse: collapse;
  background: #0f172a;
  border-radius: 8px;
  overflow: hidden;
}
.data-table th { background: #334155; padding: 1rem; text-align: left; font-weight: 600; color: #06b6d4; }
.data-table td { padding: 1rem; border-top: 1px solid #334155; }
.data-table tr:hover { background: #1e293b; }
.code-block {
  background: #0f172a;
  padding: 1.5rem;
  border-radius: 8px;
  overflow-x: auto;
  font-family: 'Monaco', 'Courier New', monospace;
  font-size: 0.9rem;
  line-height: 1.5;
  border: 1px solid #334155;
}
.code-block code { color: #06b6d4; }
.chart-container {
  background: #0f172a;
  padding: 2rem;
  border-radius: 8px;
  min-height: 300px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}
.chart-note { color: #64748b; margin-top: 1rem; font-style: italic; }
.no-data { color: #64748b; text-align: center; padding: 2rem; }
.report-footer {
  background: #0f172a;
  padding: 2rem;
  text-align: center;
  border-radius: 0 0 12px 12px;
  color: #94a3b8;
}
.footer-links { margin-top: 1rem; }
.footer-links a { color: #06b6d4; text-decoration: none; margin: 0 0.5rem; }
.footer-links a:hover { text-decoration: underline; }
@media print {
  body { background: white; padding: 0; }
  .container { box-shadow: none; }
}`;
  }

  private static getScripts(): string {
    return `
console.log('CortexOps Report Generated');
// Chart initialization would go here`;
  }
}

/**
 * Export report as file
 */
export function downloadHTMLReport(html: string, filename: string): void {
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename.endsWith('.html') ? filename : `${filename}.html`;
  a.click();
  URL.revokeObjectURL(url);
}
