/**
 * Security Audit Generator
 * Integrates CIS compliance auditing with Lynis
 */

export interface SecurityAuditConfig {
  includeLynis?: boolean;
  includeCISBenchmark?: boolean;
  includeOpenSCAP?: boolean;
  generateReport?: boolean;
  reportFormat?: 'html' | 'json' | 'txt';
}

/**
 * Generate security audit playbook task
 */
export function generateSecurityAuditTasks(config: SecurityAuditConfig = {}): string {
  const {
    includeLynis = true,
    includeCISBenchmark = true,
    includeOpenSCAP = false,
    generateReport = true,
    reportFormat = 'html'
  } = config;

  let tasks = `---
# Security Audit & CIS Compliance Tasks
# Generated by CortexOps Security Module

- name: Create audit directory
  file:
    path: /var/log/security-audit
    state: directory
    mode: '0755'
  tags: ['security', 'audit']

`;

  if (includeLynis) {
    tasks += `
- name: Install Lynis security auditing tool
  package:
    name: lynis
    state: present
  when: ansible_os_family == "Debian"
  tags: ['security', 'audit', 'lynis']

- name: Install Lynis from source (if package unavailable)
  block:
    - name: Download Lynis
      get_url:
        url: https://downloads.cisofy.com/lynis/lynis-3.0.9.tar.gz
        dest: /tmp/lynis.tar.gz
        mode: '0644'

    - name: Extract Lynis
      unarchive:
        src: /tmp/lynis.tar.gz
        dest: /opt/
        remote_src: yes
        creates: /opt/lynis

    - name: Create Lynis symlink
      file:
        src: /opt/lynis/lynis
        dest: /usr/local/bin/lynis
        state: link
  when: ansible_os_family != "Debian"
  tags: ['security', 'audit', 'lynis']

- name: Run Lynis system audit
  shell: |
    lynis audit system --quiet --no-colors > /var/log/security-audit/lynis-report-{{ ansible_date_time.date }}.txt 2>&1
  register: lynis_audit
  changed_when: false
  failed_when: false
  tags: ['security', 'audit', 'lynis']

- name: Extract Lynis security score
  shell: |
    grep 'Hardening index' /var/log/security-audit/lynis-report-{{ ansible_date_time.date }}.txt | awk -F: '{print $2}' | tr -d ' []'
  register: lynis_score
  changed_when: false
  failed_when: false
  tags: ['security', 'audit', 'lynis']

- name: Display Lynis security score
  debug:
    msg: "Lynis Security Score: {{ lynis_score.stdout | default('N/A') }}"
  tags: ['security', 'audit', 'lynis']
`;
  }

  if (includeCISBenchmark) {
    tasks += `
- name: Install CIS-CAT assessment tool dependencies
  package:
    name:
      - unzip
      - java-11-openjdk-headless
    state: present
  when: ansible_os_family == "Debian"
  tags: ['security', 'audit', 'cis']

- name: Check if CIS-CAT exists
  stat:
    path: /opt/cis-cat
  register: ciscat_dir
  tags: ['security', 'audit', 'cis']

- name: Run CIS benchmark check (manual commands)
  block:
    - name: Check SSH configuration against CIS benchmark
      shell: |
        cat <<'EOF' > /var/log/security-audit/cis-ssh-check.sh
        #!/bin/bash
        echo "=== CIS SSH Configuration Audit ==="
        echo ""

        # 5.2.1 Ensure permissions on /etc/ssh/sshd_config are configured
        echo "[5.2.1] Checking /etc/ssh/sshd_config permissions..."
        stat -L -c "%a %u %g" /etc/ssh/sshd_config | grep -q "600 0 0" && echo "PASS" || echo "FAIL"

        # 5.2.2 Ensure SSH Protocol is set to 2
        echo "[5.2.2] Checking SSH Protocol version..."
        sshd -T | grep -i "^protocol" | grep -q "2" && echo "PASS" || echo "PASS (default)"

        # 5.2.3 Ensure SSH LogLevel is appropriate
        echo "[5.2.3] Checking SSH LogLevel..."
        sshd -T | grep -i "^loglevel" | grep -qE "INFO|VERBOSE" && echo "PASS" || echo "FAIL"

        # 5.2.4 Ensure SSH X11 forwarding is disabled
        echo "[5.2.4] Checking X11 forwarding..."
        sshd -T | grep -i "^x11forwarding" | grep -q "no" && echo "PASS" || echo "FAIL"

        # 5.2.5 Ensure SSH MaxAuthTries is set to 4 or less
        echo "[5.2.5] Checking MaxAuthTries..."
        sshd -T | grep -i "^maxauthtries" | awk '{if ($2 <= 4) print "PASS"; else print "FAIL"}'

        # 5.2.6 Ensure SSH IgnoreRhosts is enabled
        echo "[5.2.6] Checking IgnoreRhosts..."
        sshd -T | grep -i "^ignorerhosts" | grep -q "yes" && echo "PASS" || echo "FAIL"

        # 5.2.7 Ensure SSH HostbasedAuthentication is disabled
        echo "[5.2.7] Checking HostbasedAuthentication..."
        sshd -T | grep -i "^hostbasedauthentication" | grep -q "no" && echo "PASS" || echo "FAIL"

        # 5.2.8 Ensure SSH root login is disabled
        echo "[5.2.8] Checking PermitRootLogin..."
        sshd -T | grep -i "^permitrootlogin" | grep -q "no" && echo "PASS" || echo "FAIL"

        # 5.2.9 Ensure SSH PermitEmptyPasswords is disabled
        echo "[5.2.9] Checking PermitEmptyPasswords..."
        sshd -T | grep -i "^permitemptypasswords" | grep -q "no" && echo "PASS" || echo "FAIL"

        # 5.2.10 Ensure SSH PermitUserEnvironment is disabled
        echo "[5.2.10] Checking PermitUserEnvironment..."
        sshd -T | grep -i "^permituserenvironment" | grep -q "no" && echo "PASS" || echo "FAIL"

        echo ""
        echo "=== CIS SSH Audit Complete ==="
        EOF
        chmod +x /var/log/security-audit/cis-ssh-check.sh
        /var/log/security-audit/cis-ssh-check.sh
      register: cis_ssh_audit
      changed_when: false
      failed_when: false
      tags: ['security', 'audit', 'cis']

    - name: Run CIS filesystem audit
      shell: |
        cat <<'EOF' > /var/log/security-audit/cis-filesystem-check.sh
        #!/bin/bash
        echo "=== CIS Filesystem Configuration Audit ==="
        echo ""

        # 1.1.2 Ensure /tmp is configured
        echo "[1.1.2] Checking /tmp mount..."
        mount | grep -q " /tmp " && echo "PASS" || echo "FAIL"

        # 1.1.3 Ensure nodev option set on /tmp partition
        echo "[1.1.3] Checking nodev on /tmp..."
        mount | grep " /tmp " | grep -q "nodev" && echo "PASS" || echo "FAIL"

        # 1.1.4 Ensure nosuid option set on /tmp partition
        echo "[1.1.4] Checking nosuid on /tmp..."
        mount | grep " /tmp " | grep -q "nosuid" && echo "PASS" || echo "FAIL"

        # 1.1.5 Ensure noexec option set on /tmp partition
        echo "[1.1.5] Checking noexec on /tmp..."
        mount | grep " /tmp " | grep -q "noexec" && echo "PASS" || echo "FAIL"

        # 1.5.1 Ensure core dumps are restricted
        echo "[1.5.1] Checking core dump restrictions..."
        grep -q "hard core 0" /etc/security/limits.conf && echo "PASS" || echo "FAIL"

        echo ""
        echo "=== CIS Filesystem Audit Complete ==="
        EOF
        chmod +x /var/log/security-audit/cis-filesystem-check.sh
        /var/log/security-audit/cis-filesystem-check.sh
      register: cis_filesystem_audit
      changed_when: false
      failed_when: false
      tags: ['security', 'audit', 'cis']
  tags: ['security', 'audit', 'cis']
`;
  }

  if (includeOpenSCAP) {
    tasks += `
- name: Install OpenSCAP
  package:
    name:
      - openscap-scanner
      - scap-security-guide
    state: present
  when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"
  tags: ['security', 'audit', 'openscap']

- name: Run OpenSCAP evaluation
  shell: |
    oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_cis \
      --results /var/log/security-audit/openscap-results-{{ ansible_date_time.date }}.xml \
      --report /var/log/security-audit/openscap-report-{{ ansible_date_time.date }}.html \
      /usr/share/xml/scap/ssg/content/ssg-{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}-ds.xml
  register: openscap_eval
  changed_when: false
  failed_when: false
  when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"
  tags: ['security', 'audit', 'openscap']
`;
  }

  if (generateReport) {
    tasks += `
- name: Generate consolidated security audit report
  template:
    src: security-audit-report.${reportFormat}.j2
    dest: /var/log/security-audit/security-audit-{{ ansible_date_time.date }}.${reportFormat}
    mode: '0644'
  tags: ['security', 'audit', 'report']

- name: Create security audit summary
  copy:
    content: |
      ========================================
      SECURITY AUDIT REPORT
      ========================================
      Date: {{ ansible_date_time.iso8601 }}
      Hostname: {{ ansible_hostname }}
      Distribution: {{ ansible_distribution }} {{ ansible_distribution_version }}

      ${includeLynis ? `Lynis Score: {{ lynis_score.stdout | default('N/A') }}` : ''}
      ${includeCISBenchmark ? `CIS Benchmark: Completed` : ''}
      ${includeOpenSCAP ? `OpenSCAP: Completed` : ''}

      Detailed reports available in: /var/log/security-audit/
      ========================================
    dest: /var/log/security-audit/audit-summary-{{ ansible_date_time.date }}.txt
    mode: '0644'
  tags: ['security', 'audit', 'report']

- name: Display audit summary location
  debug:
    msg: "Security audit reports saved to /var/log/security-audit/"
  tags: ['security', 'audit', 'report']
`;
  }

  return tasks;
}

/**
 * Generate security audit report template
 */
export function generateSecurityAuditReportTemplate(format: 'html' | 'json' | 'txt' = 'html'): string {
  if (format === 'html') {
    return `<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Security Audit Report - {{ ansible_hostname }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 30px;
        }
        .section {
            background: white;
            padding: 20px;
            border-radius: 10px;
            margin-bottom: 20px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .score {
            font-size: 48px;
            font-weight: bold;
            text-align: center;
            margin: 20px 0;
        }
        .score.good { color: #10b981; }
        .score.warning { color: #f59e0b; }
        .score.danger { color: #ef4444; }
        .metric {
            display: flex;
            justify-content: space-between;
            padding: 10px;
            border-bottom: 1px solid #e5e7eb;
        }
        .badge {
            display: inline-block;
            padding: 4px 12px;
            border-radius: 20px;
            font-size: 12px;
            font-weight: bold;
        }
        .badge.pass { background: #10b981; color: white; }
        .badge.fail { background: #ef4444; color: white; }
    </style>
</head>
<body>
    <div class="header">
        <h1>🔒 Security Audit Report</h1>
        <p><strong>Host:</strong> {{ ansible_hostname }}</p>
        <p><strong>Date:</strong> {{ ansible_date_time.iso8601 }}</p>
        <p><strong>Distribution:</strong> {{ ansible_distribution }} {{ ansible_distribution_version }}</p>
    </div>

    <div class="section">
        <h2>📊 Overall Security Score</h2>
        <div class="score {% if lynis_score.stdout | int >= 80 %}good{% elif lynis_score.stdout | int >= 60 %}warning{% else %}danger{% endif %}">
            {{ lynis_score.stdout | default('N/A') }}
        </div>
    </div>

    <div class="section">
        <h2>🔍 Audit Results</h2>
        {% if lynis_audit is defined %}
        <div class="metric">
            <span>Lynis Audit</span>
            <span class="badge pass">COMPLETED</span>
        </div>
        {% endif %}
        {% if cis_ssh_audit is defined %}
        <div class="metric">
            <span>CIS SSH Benchmark</span>
            <span class="badge pass">COMPLETED</span>
        </div>
        {% endif %}
        {% if cis_filesystem_audit is defined %}
        <div class="metric">
            <span>CIS Filesystem Audit</span>
            <span class="badge pass">COMPLETED</span>
        </div>
        {% endif %}
        {% if openscap_eval is defined %}
        <div class="metric">
            <span>OpenSCAP Evaluation</span>
            <span class="badge pass">COMPLETED</span>
        </div>
        {% endif %}
    </div>

    <div class="section">
        <h2>📋 Recommendations</h2>
        <ul>
            <li>Review detailed Lynis report at: /var/log/security-audit/lynis-report-{{ ansible_date_time.date }}.txt</li>
            <li>Implement CIS benchmark recommendations</li>
            <li>Schedule regular security audits (monthly recommended)</li>
            <li>Keep system packages up-to-date</li>
            <li>Monitor security logs regularly</li>
        </ul>
    </div>

    <div class="section">
        <h2>🔗 Resources</h2>
        <ul>
            <li><a href="https://cisofy.com/lynis/">Lynis Documentation</a></li>
            <li><a href="https://www.cisecurity.org/benchmark/">CIS Benchmarks</a></li>
            <li><a href="https://www.open-scap.org/">OpenSCAP Project</a></li>
        </ul>
    </div>

    <footer style="text-align: center; margin-top: 40px; color: #6b7280;">
        <p>Generated by CortexOps Security Module</p>
    </footer>
</body>
</html>`;
  } else if (format === 'json') {
    return `{
  "audit_date": "{{ ansible_date_time.iso8601 }}",
  "hostname": "{{ ansible_hostname }}",
  "distribution": "{{ ansible_distribution }} {{ ansible_distribution_version }}",
  "lynis_score": "{{ lynis_score.stdout | default('N/A') }}",
  "audits_completed": {
    "lynis": {% if lynis_audit is defined %}true{% else %}false{% endif %},
    "cis_ssh": {% if cis_ssh_audit is defined %}true{% else %}false{% endif %},
    "cis_filesystem": {% if cis_filesystem_audit is defined %}true{% else %}false{% endif %},
    "openscap": {% if openscap_eval is defined %}true{% else %}false{% endif %}
  },
  "report_location": "/var/log/security-audit/"
}`;
  } else {
    return `========================================
SECURITY AUDIT REPORT
========================================
Date: {{ ansible_date_time.iso8601 }}
Hostname: {{ ansible_hostname }}
Distribution: {{ ansible_distribution }} {{ ansible_distribution_version }}

Lynis Score: {{ lynis_score.stdout | default('N/A') }}

Audits Completed:
{% if lynis_audit is defined %}- Lynis Audit: COMPLETED{% endif %}
{% if cis_ssh_audit is defined %}- CIS SSH Benchmark: COMPLETED{% endif %}
{% if cis_filesystem_audit is defined %}- CIS Filesystem Audit: COMPLETED{% endif %}
{% if openscap_eval is defined %}- OpenSCAP Evaluation: COMPLETED{% endif %}

Detailed reports available in: /var/log/security-audit/
========================================`;
  }
}

/**
 * Generate complete security audit playbook
 */
export function generateSecurityAuditPlaybook(config: SecurityAuditConfig = {}): string {
  return `---
# Security Audit & CIS Compliance Playbook
# Generated by CortexOps Security Module

- name: Security Audit & CIS Compliance Check
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
${generateSecurityAuditTasks(config)}
`;
}
